# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

# CodeRabbit Configuration for the0
# Open Source Algorithmic Trading Platform

language: "en-US"

tone_instructions: "Be thorough and security-conscious. This is a trading platform where bugs can have financial consequences."

early_access: true
enable_free_tier: true

reviews:
  profile: "assertive"
  request_changes_workflow: true
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"

  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - "main"
      - "release/.*"

  path_filters:
    # Include all source code
    - "**/*.ts"
    - "**/*.tsx"
    - "**/*.js"
    - "**/*.jsx"
    - "**/*.go"
    - "**/*.py"
    - "**/*.yaml"
    - "**/*.yml"
    # Exclude generated and vendor files
    - "!**/node_modules/**"
    - "!**/dist/**"
    - "!**/build/**"
    - "!**/.next/**"
    - "!**/vendor/**"
    - "!**/*.pb.go"
    - "!**/*_grpc.pb.go"
    - "!**/coverage/**"

  path_instructions:
    - path: "frontend/**"
      instructions: |
        This is a Next.js 15 + React 19 frontend application.
        - Ensure proper TypeScript types (avoid `any`)
        - Check for React best practices (hooks rules, memo usage)
        - Verify Tailwind CSS class usage
        - Look for potential XSS vulnerabilities
        - Ensure proper error handling in API calls

    - path: "api/**"
      instructions: |
        This is a NestJS REST API for an algorithmic trading platform.
        - Security is critical - check for injection vulnerabilities
        - Verify proper authentication/authorization guards
        - Ensure DTOs have proper validation decorators
        - Check database queries for N+1 problems
        - Verify proper error handling and logging
        - Check for sensitive data exposure in responses

    - path: "runtime/**/*.go"
      instructions: |
        This is the Go runtime for bot execution (bot-runner, bot-scheduler, controller).
        - Check for proper error handling (no ignored errors)
        - Verify goroutine lifecycle management (no leaks)
        - Ensure context cancellation is properly propagated
        - Check for race conditions in concurrent code
        - Verify resource cleanup (defer statements)
        - Look for potential memory leaks

    - path: "runtime/internal/k8s/**"
      instructions: |
        Kubernetes controller code for managing bot Pods and CronJobs.
        - Verify proper RBAC permissions are documented
        - Check reconciliation logic for edge cases
        - Ensure idempotent operations
        - Verify proper label/annotation usage
        - Check for potential infinite reconciliation loops

    - path: "runtime/internal/docker-runner/**"
      instructions: |
        Docker container orchestration code.
        - Check for container escape vulnerabilities
        - Verify proper resource limits
        - Ensure proper cleanup of containers
        - Check for command injection in container commands

    - path: "cli/**/*.go"
      instructions: |
        CLI tool for bot development and deployment.
        - Verify proper input validation
        - Check for secure credential handling
        - Ensure helpful error messages
        - Verify flag parsing edge cases

    - path: "k8s/**"
      instructions: |
        Helm charts and Kubernetes manifests.
        - Verify security contexts are properly set
        - Check resource limits and requests
        - Ensure proper RBAC configuration
        - Verify no secrets in plain text
        - Check for proper health probes

    - path: "**/*_test.go"
      instructions: |
        Go test files.
        - Verify test coverage for edge cases
        - Check for proper test isolation
        - Ensure meaningful assertions
        - Look for flaky test patterns

    - path: "**/*.test.ts"
      instructions: |
        TypeScript/Jest test files.
        - Verify proper mocking
        - Check for async test handling
        - Ensure meaningful test descriptions
        - Look for proper cleanup in afterEach

  finishing_touches:
    docstrings:
      enabled: true
    unit_tests:
      enabled: true

chat:
  auto_reply: true

knowledge_base:
  opt_out: false
  web_search:
    enabled: true
  learnings:
    scope: "auto"

tools:
  # TypeScript/JavaScript
  eslint:
    enabled: true
  biome:
    enabled: true

  # Go
  golangci-lint:
    enabled: true

  # Python
  ruff:
    enabled: true

  # Security
  gitleaks:
    enabled: true
  semgrep:
    enabled: true

  # YAML/Config
  yamllint:
    enabled: true
  actionlint:
    enabled: true

  # Kubernetes
  checkov:
    enabled: true

  # Markdown
  markdownlint:
    enabled: true
  languagetool:
    enabled: true
    enabled_rules: []
    disabled_rules:
      - "MORFOLOGIK_RULE_EN_US"  # Ignore spelling for technical terms
    enabled_categories: []
    disabled_categories:
      - "TYPOS"
