name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["type/feature", "status/needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when... / It would be helpful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I also considered...

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - Frontend (Next.js UI)
        - API (NestJS backend)
        - Runtime (Bot execution services)
        - CLI (Command-line tool)
        - Infrastructure (Docker/K8s)
        - Documentation
        - Multiple components
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking my use of the0
        - High - Would significantly improve my workflow
        - Medium - Would be nice to have
        - Low - Just an idea
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case for this feature
      placeholder: |
        I want to...
        This would help me...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, examples, or screenshots about the feature request here

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched for existing feature requests to avoid duplicates
          required: true
        - label: This feature aligns with the0's vision as a production execution engine
          required: false
        - label: I am willing to help implement this feature (if possible)
          required: false
