{{- if .Values.the0AiAgent.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "the0.fullname" . }}-ai-agent
  labels:
    {{- include "the0.labels" . | nindent 4 }}
    app.kubernetes.io/component: ai-agent
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.the0AiAgent.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "the0.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ai-agent

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "the0.fullname" . }}-ai-agent
  labels:
    {{- include "the0.labels" . | nindent 4 }}
    app.kubernetes.io/component: ai-agent
spec:
  replicas: {{ .Values.the0AiAgent.replicas }}
  selector:
    matchLabels:
      {{- include "the0.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ai-agent
  template:
    metadata:
      labels:
        {{- include "the0.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ai-agent
    spec:
      containers:
        - name: ai-agent
          image: {{ .Values.the0AiAgent.image.repository }}:{{ .Values.the0AiAgent.image.tag }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.the0AiAgent.port }}
              protocol: TCP
          env:
            {{- range $key, $value := .Values.the0AiAgent.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.the0AiAgent.resources | nindent 12 }}
{{- end }}