package local

import (
	"os"
	"path/filepath"

	"the0/internal/logger"
)

// defaultEnvContent contains the default .env values matching the compose file
const defaultEnvContent = `# the0 Local Environment Configuration
# Generated by the0 CLI - edit as needed

# PostgreSQL
POSTGRES_DB=the0_oss
POSTGRES_USER=the0
POSTGRES_PASSWORD=the0_password

# MongoDB
MONGO_INITDB_ROOT_USERNAME=root
MONGO_INITDB_ROOT_PASSWORD=the0_mongo_password
MONGO_INITDB_DATABASE=bot_runner

# MinIO
MINIO_ROOT_USER=the0admin
MINIO_ROOT_PASSWORD=the0password

# JWT
JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
JWT_EXPIRES_IN=24h

# API
API_PORT=3000
FRONTEND_PORT=3001
DOCS_PORT=3002
`

// GenerateEnvFile writes a .env file with default values to the compose directory.
// It does not overwrite an existing .env file.
func GenerateEnvFile(composeDir string) error {
	envPath := filepath.Join(composeDir, ".env")

	if _, err := os.Stat(envPath); err == nil {
		logger.Verbose("Skipping .env generation (already exists)")
		return nil
	}

	if err := os.WriteFile(envPath, []byte(defaultEnvContent), 0600); err != nil {
		return err
	}

	logger.Verbose("Generated .env file at %s", envPath)
	return nil
}
