package local

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"the0/internal/logger"
)

var adminEmailPattern = regexp.MustCompile(`^[A-Za-z0-9.!#$%&'*+/=?^_{|}~-]+@[A-Za-z0-9-]+(?:\.[A-Za-z0-9-]+)+$`)

// defaultEnvContent contains the default .env values matching the compose file
const defaultEnvContent = `# the0 Local Environment Configuration
# Generated by the0 CLI - edit as needed

# PostgreSQL
POSTGRES_DB=the0_oss
POSTGRES_USER=the0
POSTGRES_PASSWORD=the0_password

# MongoDB
MONGO_INITDB_ROOT_USERNAME=root
MONGO_INITDB_ROOT_PASSWORD=the0_mongo_password
MONGO_INITDB_DATABASE=bot_runner

# MinIO
MINIO_ROOT_USER=the0admin
MINIO_ROOT_PASSWORD=the0password

# JWT
JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
JWT_EXPIRES_IN=24h

# Root admin
THE0_ADMIN_EMAIL=
THE0_ADMIN_PASSWORD=

# API
API_PORT=3000
FRONTEND_PORT=3001
DOCS_PORT=3002

# Docker socket access for non-root runtime services
DOCKER_GID={{DOCKER_GID}}
`

// GenerateEnvFile writes a .env file with default values to the compose directory.
// It preserves existing values and appends newly required defaults.
func GenerateEnvFile(composeDir string) error {
	envPath := filepath.Join(composeDir, ".env")
	dockerGID := detectDockerSocketGID()
	defaults := strings.ReplaceAll(defaultEnvContent, "{{DOCKER_GID}}", dockerGID)

	if _, err := os.Stat(envPath); err == nil {
		data, err := os.ReadFile(envPath)
		if err != nil {
			return fmt.Errorf("failed to read existing env file: %w", err)
		}
		content := string(data)
		missingAdminEmail := !hasEnvKey(content, "THE0_ADMIN_EMAIL")
		missingAdminPassword := !hasEnvKey(content, "THE0_ADMIN_PASSWORD")
		if missingAdminEmail {
			block := "\n# Root admin\nTHE0_ADMIN_EMAIL=\n"
			if missingAdminPassword {
				block += "THE0_ADMIN_PASSWORD=\n"
			}
			if err := appendEnvBlock(envPath, block); err != nil {
				return err
			}
			logger.Verbose("Updated .env file with THE0_ADMIN_EMAIL")
		}
		if !missingAdminEmail && missingAdminPassword {
			if err := appendEnvBlock(envPath, "\nTHE0_ADMIN_PASSWORD=\n"); err != nil {
				return err
			}
			logger.Verbose("Updated .env file with THE0_ADMIN_PASSWORD")
		}
		if !hasEnvKey(content, "DOCKER_GID") {
			f, err := os.OpenFile(envPath, os.O_APPEND|os.O_WRONLY, 0600)
			if err != nil {
				return fmt.Errorf("failed to update env file: %w", err)
			}
			defer f.Close()
			if _, err := fmt.Fprintf(f, "\n# Docker socket access for non-root runtime services\nDOCKER_GID=%s\n", dockerGID); err != nil {
				return fmt.Errorf("failed to append Docker GID to env file: %w", err)
			}
			logger.Verbose("Updated .env file with DOCKER_GID")
		}
		logger.Verbose("Skipping .env generation (already exists)")
		return nil
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("failed to check env file: %w", err)
	}

	if err := os.WriteFile(envPath, []byte(defaults), 0600); err != nil {
		return err
	}

	logger.Verbose("Generated .env file at %s", envPath)
	return nil
}

func hasEnvKey(content, key string) bool {
	prefix := key + "="
	for _, line := range strings.Split(content, "\n") {
		if strings.HasPrefix(strings.TrimSpace(line), prefix) {
			return true
		}
	}
	return false
}

// SetAdminEmail updates THE0_ADMIN_EMAIL in the local compose .env file.
func SetAdminEmail(composeDir string, email string) error {
	return SetAdminCredentials(composeDir, email, "")
}

// SetAdminPassword updates THE0_ADMIN_PASSWORD while preserving the configured
// admin email.
func SetAdminPassword(composeDir string, password string) error {
	if err := ValidateAdminPassword(password); err != nil {
		return err
	}

	envPath := filepath.Join(composeDir, ".env")
	data, err := os.ReadFile(envPath)
	if err != nil {
		if os.IsNotExist(err) {
			return fmt.Errorf(".env not found in %s; run `the0 local init` first", composeDir)
		}
		return fmt.Errorf("failed to read .env file: %w", err)
	}

	content := string(data)
	if envValue(content, "THE0_ADMIN_EMAIL") == "" {
		return fmt.Errorf("THE0_ADMIN_EMAIL is not configured; run `the0 local admin set --email you@example.com` first")
	}

	content = upsertEnvValue(content, "THE0_ADMIN_PASSWORD", password)
	if err := os.WriteFile(envPath, []byte(content), 0600); err != nil {
		return fmt.Errorf("failed to write .env file: %w", err)
	}

	return nil
}

// SetAdminCredentials updates THE0_ADMIN_EMAIL and THE0_ADMIN_PASSWORD in the
// local compose .env file.
func SetAdminCredentials(composeDir string, email string, password string) error {
	email = strings.TrimSpace(email)
	if err := ValidateAdminEmail(email); err != nil {
		return err
	}
	if password != "" {
		if err := ValidateAdminPassword(password); err != nil {
			return err
		}
	}

	envPath := filepath.Join(composeDir, ".env")
	data, err := os.ReadFile(envPath)
	if err != nil {
		if os.IsNotExist(err) {
			return fmt.Errorf(".env not found in %s; run `the0 local init` first", composeDir)
		}
		return fmt.Errorf("failed to read .env file: %w", err)
	}

	content := upsertEnvValue(string(data), "THE0_ADMIN_EMAIL", email)
	if password != "" {
		content = upsertEnvValue(content, "THE0_ADMIN_PASSWORD", password)
	}

	if err := os.WriteFile(envPath, []byte(content), 0600); err != nil {
		return fmt.Errorf("failed to write .env file: %w", err)
	}

	return nil
}

// AdminCredentialsConfigured returns whether local compose has both root admin
// credentials set.
func AdminCredentialsConfigured(composeDir string) (bool, error) {
	envPath := filepath.Join(composeDir, ".env")
	data, err := os.ReadFile(envPath)
	if err != nil {
		if os.IsNotExist(err) {
			return false, fmt.Errorf(".env not found in %s; run `the0 local init` first", composeDir)
		}
		return false, fmt.Errorf("failed to read .env file: %w", err)
	}

	content := string(data)
	return envValue(content, "THE0_ADMIN_EMAIL") != "" &&
		envValue(content, "THE0_ADMIN_PASSWORD") != "", nil
}

func envValue(content string, key string) string {
	prefix := key + "="
	for _, line := range strings.Split(content, "\n") {
		trimmed := strings.TrimSpace(line)
		if !strings.HasPrefix(trimmed, prefix) {
			continue
		}
		value := strings.TrimSpace(strings.TrimPrefix(trimmed, prefix))
		if hashIndex := strings.Index(value, "#"); hashIndex >= 0 {
			value = strings.TrimSpace(value[:hashIndex])
		}
		return value
	}
	return ""
}

func upsertEnvValue(content string, key string, value string) string {
	lines := strings.Split(content, "\n")
	found := false
	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, key+"=") {
			lines[i] = key + "=" + value + trailingInlineComment(line)
			found = true
		}
	}

	updated := strings.Join(lines, "\n")
	if found {
		return updated
	}

	if strings.TrimSpace(updated) != "" && !strings.HasSuffix(updated, "\n") {
		updated += "\n"
	}
	if !hasEnvKey(updated, "THE0_ADMIN_EMAIL") && !hasEnvKey(updated, "THE0_ADMIN_PASSWORD") {
		updated += "\n# Root admin\n"
	}
	updated += key + "=" + value + "\n"
	return updated
}

func trailingInlineComment(line string) string {
	hashIndex := strings.Index(line, "#")
	if hashIndex == -1 {
		return ""
	}
	return " " + strings.TrimSpace(line[hashIndex:])
}

// ValidateAdminEmail checks that an admin email can be safely written to .env.
func ValidateAdminEmail(email string) error {
	if email == "" {
		return fmt.Errorf("email is required")
	}
	if strings.ContainsAny(email, "\r\n=") || !adminEmailPattern.MatchString(email) {
		return fmt.Errorf("email must be a valid single-line email address")
	}
	return nil
}

// ValidateAdminPassword checks that an admin password can be safely written to .env.
// The API owns password policy validation and fails startup when the configured
// root admin password is invalid.
func ValidateAdminPassword(password string) error {
	if password == "" {
		return fmt.Errorf("password is required")
	}
	if strings.TrimSpace(password) != password {
		return fmt.Errorf("password must not start or end with whitespace")
	}
	if strings.ContainsAny(password, "\r\n=#") {
		return fmt.Errorf("password must be a single-line .env value")
	}
	return nil
}

func appendEnvBlock(envPath string, block string) error {
	f, err := os.OpenFile(envPath, os.O_APPEND|os.O_WRONLY, 0600)
	if err != nil {
		return fmt.Errorf("failed to update env file: %w", err)
	}
	defer f.Close()
	if _, err := f.WriteString(block); err != nil {
		return fmt.Errorf("failed to append to env file: %w", err)
	}
	return nil
}
