package local

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"the0/internal/logger"
)

// defaultEnvContent contains the default .env values matching the compose file
const defaultEnvContent = `# the0 Local Environment Configuration
# Generated by the0 CLI - edit as needed

# PostgreSQL
POSTGRES_DB=the0_oss
POSTGRES_USER=the0
POSTGRES_PASSWORD=the0_password

# MongoDB
MONGO_INITDB_ROOT_USERNAME=root
MONGO_INITDB_ROOT_PASSWORD=the0_mongo_password
MONGO_INITDB_DATABASE=bot_runner

# MinIO
MINIO_ROOT_USER=the0admin
MINIO_ROOT_PASSWORD=the0password

# JWT
JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
JWT_EXPIRES_IN=24h

# Admin bootstrap
THE0_ADMIN_EMAIL=

# API
API_PORT=3000
FRONTEND_PORT=3001
DOCS_PORT=3002

# Docker socket access for non-root runtime services
DOCKER_GID={{DOCKER_GID}}
`

// GenerateEnvFile writes a .env file with default values to the compose directory.
// It preserves existing values and appends newly required defaults.
func GenerateEnvFile(composeDir string) error {
	envPath := filepath.Join(composeDir, ".env")
	dockerGID := detectDockerSocketGID()
	defaults := strings.ReplaceAll(defaultEnvContent, "{{DOCKER_GID}}", dockerGID)

	if _, err := os.Stat(envPath); err == nil {
		data, err := os.ReadFile(envPath)
		if err != nil {
			return fmt.Errorf("failed to read existing env file: %w", err)
		}
		content := string(data)
		if !hasEnvKey(content, "THE0_ADMIN_EMAIL") {
			if err := appendEnvBlock(envPath, "\n# Admin bootstrap\nTHE0_ADMIN_EMAIL=\n"); err != nil {
				return err
			}
			logger.Verbose("Updated .env file with THE0_ADMIN_EMAIL")
		}
		if !hasEnvKey(content, "DOCKER_GID") {
			f, err := os.OpenFile(envPath, os.O_APPEND|os.O_WRONLY, 0600)
			if err != nil {
				return fmt.Errorf("failed to update env file: %w", err)
			}
			defer f.Close()
			if _, err := fmt.Fprintf(f, "\n# Docker socket access for non-root runtime services\nDOCKER_GID=%s\n", dockerGID); err != nil {
				return fmt.Errorf("failed to append Docker GID to env file: %w", err)
			}
			logger.Verbose("Updated .env file with DOCKER_GID")
		}
		logger.Verbose("Skipping .env generation (already exists)")
		return nil
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("failed to check env file: %w", err)
	}

	if err := os.WriteFile(envPath, []byte(defaults), 0600); err != nil {
		return err
	}

	logger.Verbose("Generated .env file at %s", envPath)
	return nil
}

func hasEnvKey(content, key string) bool {
	prefix := key + "="
	for _, line := range strings.Split(content, "\n") {
		if strings.HasPrefix(strings.TrimSpace(line), prefix) {
			return true
		}
	}
	return false
}

// SetAdminEmail updates THE0_ADMIN_EMAIL in the local compose .env file.
func SetAdminEmail(composeDir string, email string) error {
	email = strings.TrimSpace(email)
	if email == "" {
		return fmt.Errorf("email is required")
	}

	envPath := filepath.Join(composeDir, ".env")
	data, err := os.ReadFile(envPath)
	if err != nil {
		return fmt.Errorf("failed to read .env file: %w", err)
	}

	lines := strings.Split(string(data), "\n")
	found := false
	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "THE0_ADMIN_EMAIL=") {
			lines[i] = "THE0_ADMIN_EMAIL=" + email
			found = true
		}
	}

	content := strings.Join(lines, "\n")
	if !found {
		if strings.TrimSpace(content) != "" && !strings.HasSuffix(content, "\n") {
			content += "\n"
		}
		content += "\n# Admin bootstrap\nTHE0_ADMIN_EMAIL=" + email + "\n"
	}

	if err := os.WriteFile(envPath, []byte(content), 0600); err != nil {
		return fmt.Errorf("failed to write .env file: %w", err)
	}

	return nil
}

func appendEnvBlock(envPath string, block string) error {
	f, err := os.OpenFile(envPath, os.O_APPEND|os.O_WRONLY, 0600)
	if err != nil {
		return fmt.Errorf("failed to update env file: %w", err)
	}
	defer f.Close()
	if _, err := f.WriteString(block); err != nil {
		return fmt.Errorf("failed to append to env file: %w", err)
	}
	return nil
}
